resource_labels = { "provider" : "jx" }
jx_git_url = "https://github.com/juanpa12121/jx3-demo-walk-cluster"
gcp_project = "jenkins-x-labs-bdd"
gsm = true
jx_git_url = "https://github.com/juanpa12121/jx3-demo-walk-infra.git"
gcp_project = "my-jenkinsx-project"
gsm = true
jx_git_url = "https://github.com/juanpa12121/jx3-demo-walk-cluster"
gcp_project = "jenkins-x-labs-bdd"
